[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/icons/*"
  to = "/icons/:splat"
  status = 200
  force = false
[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200
  force = false
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = false
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
